---
downloads: ~/.ansible-downloads/

configure_osx: true
configure_dotfiles: false
configure_jenkins: true
configure_jenkins_mac: true
configure_jenkins_linux: false
jenkins_home_path: ~/.jenkins

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - openjdk
  - autoconf
  - bash-completion
  - gifsicle
  - git
  - github/gh/gh
  - gpg
  - mcrypt
  - node
  - nvm
  - openssl
  - wget
  - carthage
  - jenkins-lts
  - jcli
  - jq

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - jenkins-zh/jcli
  - adoptopenjdk/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-sdk
  - android-ndk
  - docker
  - firefox
  - google-chrome
  - vagrant
  - adoptopenjdk11

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages:
  - name: bundler
    state: present  # present/absent/latest, default: present
    version: "~> 2.0.2"  # default: N/A
  - name: xcode-install
    state: present  # present/absent/latest, default: present
    # version: "~> 2.0.2" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
jenkins_plugins:
  - name: configuration-as-code


post_provision_tasks: []
