---
downloads: ~/.ansible-downloads/

configure_osx: true


homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - adoptopenjdk/openjdk/adoptopenjdk11
  - autoconf
  - bash-completion
  - gifsicle
  - git
  - github/gh/gh
  - gpg
  - mcrypt
  - node
  - nvm
  - openssl
  - wget
  - android-sdk
  - android-ndk
  - carthage

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - vagrant

osx_script: "~/.osx --no-restart"


post_provision_tasks: []
