---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - import_tasks: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ["post"]

    - name: Start Jenkins (Darwin)
      command: /usr/local/bin/brew services start jenkins-lts
      register: startJenkins_result
      when:
        - configure_jenkins

    - name: Wait for file to exist
      wait_for:
        path: ~/.jenkins/secrets/initialAdminPassword
        state: present
        timeout: 300

    - name: Get Jenkins inital password
      command: cat ~/.jenkins/secrets/initialAdminPassword
      register: initalAdmin_result
      changed_when: false
      when:
        - initalAdmin is undefined
        - configure_jenkins
        - startJenkins_result is defined

    - name: Define initalAdmin variable.
      set_fact:
        initalAdmin: "{{ initalAdmin_result.stdout }}"
      when:
        - initalAdmin is undefined
        - configure_jenkins

    - name: Creating a file with content
      copy:
        dest: "~/.jenkins-cli.yaml"
        content: |
          current: localServer
          jenkins_servers:
          - name: localServer
            url: http://localhost:8080/jenkins
            username: admin
            token: "{{ initalAdmin_result.stdout }}"
            insecureSkipVerify: true
          mirrors:
          - name: default
            url: http://mirrors.jenkins.io/
      when:
        - initalAdmin is defined
        - configure_jenkins
